// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bra_reint_API.Data;

#nullable disable

namespace bra_reint_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250408225232_ManyToMany")]
    partial class ManyToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("bra_reint_API.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostalCodeId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PostalCodeId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("bra_reint_API.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("bra_reint_API.Models.BookingToBookingType", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookingTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookingId", "BookingTypeId");

                    b.HasIndex("BookingTypeId");

                    b.ToTable("BookingBookingTypes");
                });

            modelBuilder.Entity("bra_reint_API.Models.BookingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BookingTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Vasker vinduer nøye og bra.",
                            Price = 5000m,
                            TypeName = "Vasking av vinduer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Spyler tak rent for mose og shit.",
                            Price = 7500m,
                            TypeName = "Spyling tak"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Vasker søppelbøtter rene og luktfrie.",
                            Price = 500m,
                            TypeName = "Vask søppelbøtter"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Alle våre servicer i en bestilling.",
                            Price = 20000m,
                            TypeName = "Full service"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Vasker husvegger. Perfekt før maling.",
                            Price = 7500m,
                            TypeName = "Vask husvegger"
                        });
                });

            modelBuilder.Entity("bra_reint_API.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("bra_reint_API.Models.PostalCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("PostalCodes");

                    b.HasData(
                        new
                        {
                            Code = "8800",
                            City = "Sandnessjøen"
                        },
                        new
                        {
                            Code = "8801",
                            City = "Sandnessjøen"
                        },
                        new
                        {
                            Code = "8802",
                            City = "Sandnessjøen"
                        },
                        new
                        {
                            Code = "8803",
                            City = "Sandnessjøen"
                        },
                        new
                        {
                            Code = "8804",
                            City = "Sandnessjøen"
                        },
                        new
                        {
                            Code = "8805",
                            City = "Sandnessjøen"
                        });
                });

            modelBuilder.Entity("bra_reint_API.Models.Address", b =>
                {
                    b.HasOne("bra_reint_API.Models.PostalCode", "PostalCode")
                        .WithMany("Addresses")
                        .HasForeignKey("PostalCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostalCode");
                });

            modelBuilder.Entity("bra_reint_API.Models.Booking", b =>
                {
                    b.HasOne("bra_reint_API.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("bra_reint_API.Models.BookingToBookingType", b =>
                {
                    b.HasOne("bra_reint_API.Models.Booking", "Booking")
                        .WithMany("BookingBookingTypes")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bra_reint_API.Models.BookingType", "BookingType")
                        .WithMany("BookingToBookingTypes")
                        .HasForeignKey("BookingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("BookingType");
                });

            modelBuilder.Entity("bra_reint_API.Models.Customer", b =>
                {
                    b.HasOne("bra_reint_API.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("bra_reint_API.Models.Booking", b =>
                {
                    b.Navigation("BookingBookingTypes");
                });

            modelBuilder.Entity("bra_reint_API.Models.BookingType", b =>
                {
                    b.Navigation("BookingToBookingTypes");
                });

            modelBuilder.Entity("bra_reint_API.Models.PostalCode", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
